// Code generated by MockGen. DO NOT EDIT.
// Source: ../collector.go
//
// Generated by this command:
//
//	mockgen -source=../collector.go -destination=collector.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	collector "github.com/osapi-io/gohai/internal/collector"
	gomock "go.uber.org/mock/gomock"
)

// MockCollector is a mock of Collector interface.
type MockCollector struct {
	ctrl     *gomock.Controller
	recorder *MockCollectorMockRecorder
	isgomock struct{}
}

// MockCollectorMockRecorder is the mock recorder for MockCollector.
type MockCollectorMockRecorder struct {
	mock *MockCollector
}

// NewMockCollector creates a new mock instance.
func NewMockCollector(ctrl *gomock.Controller) *MockCollector {
	mock := &MockCollector{ctrl: ctrl}
	mock.recorder = &MockCollectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollector) EXPECT() *MockCollectorMockRecorder {
	return m.recorder
}

// Category mocks base method.
func (m *MockCollector) Category() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Category")
	ret0, _ := ret[0].(string)
	return ret0
}

// Category indicates an expected call of Category.
func (mr *MockCollectorMockRecorder) Category() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Category", reflect.TypeOf((*MockCollector)(nil).Category))
}

// Collect mocks base method.
func (m *MockCollector) Collect(ctx context.Context, prior collector.PriorResults) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collect", ctx, prior)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Collect indicates an expected call of Collect.
func (mr *MockCollectorMockRecorder) Collect(ctx, prior any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MockCollector)(nil).Collect), ctx, prior)
}

// DefaultEnabled mocks base method.
func (m *MockCollector) DefaultEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// DefaultEnabled indicates an expected call of DefaultEnabled.
func (mr *MockCollectorMockRecorder) DefaultEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultEnabled", reflect.TypeOf((*MockCollector)(nil).DefaultEnabled))
}

// Dependencies mocks base method.
func (m *MockCollector) Dependencies() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dependencies")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Dependencies indicates an expected call of Dependencies.
func (mr *MockCollectorMockRecorder) Dependencies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dependencies", reflect.TypeOf((*MockCollector)(nil).Dependencies))
}

// Name mocks base method.
func (m *MockCollector) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockCollectorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockCollector)(nil).Name))
}
